version: '3.7'
services:
  user-database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users
    ports:
    - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: