version: '2.4'
services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"
    environment:
      REACT_APP_BACKEND_URL: http://172.16.4.209:5000/api
    restart: always
  api:
    image: "${API_IMAGE}"
    environment:
      DB_NAME: users
      DB_USER: ${DB_USER}
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      JWT_KEY: ${JWT_KEY}
    ports:
      - "5000:5000"
    restart: always
  db:
    image: "${DB_IMAGE}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /var/lib/postgresql/data
  